[env]
JULIA_DEPOT_PATH = "{SITE_DESTINATION}/depot"
JULIAUP_DEPOT_PATH = "{SITE_DESTINATION}/depot"
INSTALL_DIR = "{SITE_DESTINATION}"
SITE_CONFIG_DIR = "{SITE_CONFIG_DIR}"
INSTALL_VERSION = "{INSTALL_VERSION}"

[install]
versions = ["1.11.3", "1.10.8", "1.9.4", "1.8.5"]
prefix = "{SITE_DESTINATION}/depot/juliaup/"
# note: this is Lua regex: you will need to escape - and + (using %)
format = "^julia%-{INSTALL_VERSION}%+.*$"
# (optional) relocate after install
destination = "{SITE_DESTINATION}/{INSTALL_VERSION}"
stage = false

[module]
INSTALL_VERSION = "{INSTALL_VERSION}"
JULIA_PATH = "{INSTALL_DIR}/bin"

[post]
# toggles mandatory relocate if `stage` and `clean` are true. If the install
# script already relocates the package, then we can set `safe = false`
safe = true
# delete staging aread after successful install
clean = false
