[constant]
template_version = 1
cray = true

prg_env = "intel"
mpi_mod = "cray-mpich"

mpi_abi = "MPICH"
mpi_lib = "libmpi_intel.so"
srun_cmd = "srun"

cclibs = '"darshan", "lustreapi", "z", "cupti", "cudart", "cuda", "sci_intel_mpi", "sci_intel", "dl", "dsmml", "xpmem"'

[product]
cuda_version = ["11.7", "12.0", "12.2", "12.4"]
