[env]
INSTALL_NAME = "{SITE_NAME}"
INSTALL_DIR = "{SITE_DESTINATION}"
INSTALL_VERSION = "{INSTALL_VERSION}"
INSTALL_VARIANT = "{SITE_VARIANT}"
INSTALL_VERSION_VARIANT = "{INSTALL_VERSION_VARIANT}"
DL_SOURCE = "https://github.com/eschnett/MPIwrapper/archive/refs/tags"

N_PROCS = 8

[install]
versions = ["2.11.0"]
prefix = "{SITE_DESTINATION}"
# note: this is Lua regex: you will need to escape - and + (using %)
format = "^{INSTALL_VERSION_VARIANT}$"
# (optional) relocate after install
destination = "{SITE_DESTINATION}/{INSTALL_VERSION_VARIANT}"
stage = true

[module]
INSTALL_VERSION = "{INSTALL_VERSION}"
INSTALL_VARIANT = "{SITE_VARIANT}"
MPIWRAPPER_PATH = "{INSTALL_DIR}"

[post]
# toggles mandatory relocate if `stage` and `clean` are true. If the install
# script already relocates the package, then we can set `safe = false`
safe = false
# delete staging aread after successful install
clean = true
