[env]
JULIA_DEPOT_PATH = "{INSTALL_ROOT}/depot"
JULIAUP_DEPOT_PATH = "{INSTALL_ROOT}/depot"
INSTALL_DIR = "{INSTALL_ROOT}"
INSTALL_RESOURCES = "{RESOURCE_PATH}"
INSTALL_VERSION = "{VERSION}"

[install]
versions = ["1.9.4", "1.9.3", "1.9.2", "1.8.5"]
prefix = "{INSTALL_ROOT}/depot/juliaup/"
format = "julia[-]{VERSION}[+].*$"  # note: this is Lua regex: you will need to escape - and + (using square brackets)
destination = "{INSTALL_ROOT}/{VERSION}"  # relocate after install

[module]
JULIA_LOAD_PATH_PREFIX = "{INSTALL_ROOT}/environments/{VERSION}"
JULIA_PATH = "{INSTALL_DIR}/bin:{INSTALL_ROOT}/bin"
